---

service_definitions:
  traefik:
    name: traefik
    template_name: "traefik/traefik"
    environments:
      - "{{ environments.prod }}"
    files:
      - name: "traefik/acme.json"
        overwrite: false
        mode: "0600"
    networks:
      - name: "common_dev_traefik"
        driver: "overlay"
      - name: "common_prod_traefik"
        driver: "overlay"
  visualizer:
    name: visualizer
    image: dockersamples/visualizer
    internal_port: 8080
    environments:
      - "{{ environments.prod }}"
    constraints:
      - "node.role == manager"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    features:
      - "secure"
  web:
    name: web
    image: httpd
    internal_port: 8080
    environments:
      - "{{ environments.prod }}"
    constraints:
      - "node.role == manager"
      - "node.labels.environment == prod"
    features:
      - "secure"
    labels:
      - "traefik.frontend.redirect.regex=^.*"
      - "traefik.frontend.redirect.replacement=https://linkedin.com/in/martinpanzer/"