---
- name: Create directory for service definitions
  file:
    path: "{{ docker_service_dir }}/{{ service.name }}"
    state: directory

- name: Copy service definition to remote
  template:
    src: "files/{{ service.template_name | default('common') }}.j2"
    dest: "{{ docker_service_dir }}/{{ service.name }}/{{ service.name }}.yml"

- name: Copy additional configuration files to remote
  copy:
    src: "files/{{ file.name }}"
    dest: "{{ docker_service_dir }}/{{ service.name }}/{{ file.name | basename }}"
    force: "{{ file.overwrite }}"
    mode: "{{ file.mode | default('0644') }}"
  when: "service.files is defined"
  loop: "{{ service.files }}"
  loop_control:
    loop_var: "file"

- name: Update Service
  shell: docker stack deploy -c "{{ docker_service_dir }}"/"{{ service.name }}"/"{{ service.name }}".yml "{{ stack.name }}"
